<?php
/**
 * Language labels for database tables/fields belonging to extension "wec_sermons"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tx_wecsermons_resources' => 'Resources',	
		'tx_wecsermons_resources.description' => 'Description',	
		'tx_wecsermons_resources.title' => 'Title',	
		'tx_wecsermons_resources.graphic' => 'Graphic',	
		'tx_wecsermons_resources.type' => 'Type',	
		'tx_wecsermons_resources.file' => 'File',	
		'tx_wecsermons_resource_type' => 'Resource Type',	
		'tx_wecsermons_resource_type.description' => 'Description',	
		'tx_wecsermons_resource_type.name' => 'Name',	
		'tx_wecsermons_resource_type.graphic' => 'Graphic',	
		'tx_wecsermons_sermons' => 'Sermons',	
		'tx_wecsermons_sermons.title' => 'Sermon Title',	
		'tx_wecsermons_sermons.occurance_date' => 'Occurance Date',	
		'tx_wecsermons_sermons.description' => 'Short Description',	
		'tx_wecsermons_sermons.related_scripture' => 'Scripture References (Comma separated)',	
		'tx_wecsermons_sermons.keywords' => 'Keywords',	
		'tx_wecsermons_sermons.graphic' => 'Graphic',	
		'tx_wecsermons_sermons.series_uid' => 'Related Sermon Series',	
		'tx_wecsermons_sermons.topic_uid' => 'Related Topic',	
		'tx_wecsermons_sermons.record_type.I.0' => 'Sermon',	
		'tx_wecsermons_sermons.record_type.I.1' => 'Article',	
		'tx_wecsermons_sermons.record_type.I.2' => 'Study Guide',	
		'tx_wecsermons_sermons.record_type.I.3' => 'Training Material',	
		'tx_wecsermons_sermons.record_type' => 'Record Type',	
		'tx_wecsermons_sermons.resources_uid' => 'Related Resources',	
		'tx_wecsermons_series' => 'Series',	
		'tx_wecsermons_series.title' => 'Title',	
		'tx_wecsermons_series.description' => 'Description',	
		'tx_wecsermons_series.scripture' => 'Scripture Reference',	
		'tx_wecsermons_series.startdate' => 'Start Date',	
		'tx_wecsermons_series.enddate' => 'End Date',	
		'tx_wecsermons_series.graphic' => 'Graphic',	
		'tx_wecsermons_series.liturgical_season_uid' => 'Liturgical Season',	
		'tx_wecsermons_topics' => 'Topics',	
		'tx_wecsermons_topics.description' => 'Description',	
		'tx_wecsermons_topics.name' => 'Name',	
		'tx_wecsermons_liturgical_season' => 'Liturgical Season',	
		'tx_wecsermons_liturgical_season.season_name' => 'Season Name',	
		'tt_content.list_type_pi1' => 'Sermon Repository',	
		'tx_wecsermons.pi_flexform.tutorial' => 'Choose your Tutorial:',	
		'tx_wecsermons.pi_flexform.tutorial.I.0' => 'Ginghamsburg',	
		'tx_wecsermons.pi_flexform.tutorial.I.1' => 'Living Water',	
		'tx_wecsermons.pi_flexform.display' => 'What to Display:',
		'tx_wecsermons.pi_flexform.display.I.0' => 'SINGLE',
		'tx_wecsermons.pi_flexform.display.I.1' => 'LIST',
		'tx_wecsermons.pi_flexform.display.I.2' => 'RSS',
		'tx_wecsermons.pi_flexform.display.I.3' => 'ARCHIVE',
		'tx_wecsermons.pi_flexform.display.I.4' => 'SEARCH',
		'tx_wecsermons.pi_flexform.template' => 'Template File:',	
	),
);
?>